package com.gigforce.audit.controller;

import com.gigforce.audit.entity.AuditLog;
import com.gigforce.audit.service.AuditService;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.tags.Tag;
import org.springframework.http.ResponseEntity;
import org.springframework.security.access.prepost.PreAuthorize;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;

import java.util.List;

@RestController
@RequestMapping("/api/v1/audit")
@Tag(name = "Audit Management", description = "Endpoints for retrieving system activity and action logs")
public class AuditController {

    private final AuditService auditService;

    public AuditController(AuditService auditService) {
        this.auditService = auditService;
    }

    @GetMapping("/user/{userId}")
    @PreAuthorize("hasRole('ADMIN')")
    @Operation(summary = "Get audit logs by user ID", description = "Retrieves all audit logs generated by or relating to a specific user. Restricted to ADMIN users.")
    public ResponseEntity<List<AuditLog>> getAuditLogsForUser(@PathVariable Long userId) {
        List<AuditLog> logs = auditService.getAuditLogsForUser(userId);
        return ResponseEntity.ok(logs);
    }
}
