package com.gigforce.invoice.dto;

import com.fasterxml.jackson.annotation.JsonAlias;
import com.fasterxml.jackson.annotation.JsonProperty;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Positive;
import lombok.*;

import java.math.BigDecimal;
import java.time.LocalDate;

/**
 * DTO for creating new payments (POST operation).
 * Only accepts essential payment details; status and transactionId are auto-generated by the system.
 */
@Data
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class PaymentCreateRequestDTO {

    @JsonProperty("InvoiceID")
    @JsonAlias({"invoiceId", "invoiceID"})
    @NotBlank(message = "InvoiceID is required")
    private String invoiceId;

    @JsonProperty("PaidAmount")
    @JsonAlias({"paidAmount", "paid_amount"})
    @NotNull(message = "PaidAmount is required")
    @Positive(message = "PaidAmount must be positive")
    private BigDecimal paidAmount;

    @JsonProperty("PaymentDate")
    @JsonAlias({"paymentDate", "payment_date"})
    @NotNull(message = "PaymentDate is required")
    private LocalDate paymentDate;

    @JsonProperty("PaymentMode")
    @JsonAlias({"paymentMode", "payment_mode"})
    @NotBlank(message = "PaymentMode is required")
    private String paymentMode;

    // NOTE: The following fields are managed by the backend and NOT accepted from the request:
    // - status: automatically set to PENDING when payment is created
    // - transactionId: auto-generated by the system upon successful payment processing
    // - paymentReference: optional external reference, set by backend if needed
}

